# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cbd6852bb7437f3beac586131f00f559"
name = "app-test"
handle = "app-test-709"
application_url = "https://writes-dozen-liver-ceiling.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://writes-dozen-liver-ceiling.trycloudflare.com/auth/callback",
  "https://writes-dozen-liver-ceiling.trycloudflare.com/auth/shopify/callback",
  "https://writes-dozen-liver-ceiling.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
